
var contenido = {

	descripciones: [{
		EstatuaLibertad: "<p><b>La Estatua de la Libertad</b> es, sin duda, el símbolo más famoso de <b>Nueva York.</b> Su lema es: La libertad esclarece el mundo.</p> <p>Este monumento de 46 metros de altura (93 si contamos la base) se encuentra situada en Liberty Island (la isla de la libertad), y para visitarla es necesario ir en Ferry. El muelle se encuentra en Battery Park, al sur de Manhattan.</p>",
		EstatuaLibertad2: "<h3>¿Sabías que...</h3><p>...La Estatua de la Libertad fue un regalo de los franceses a los estadounidenses en 1886 para conmemorar el centenario de la Declaración de Independencia de los Estados Unidos y como un signo de amistad entre las dos naciones?.</p><p>...Desde su inauguración en 1886, la estatua fue la primera visión que tenían los inmigrantes europeos al llegar a Estados Unidos tras su travesía por el océano Atlántico?.</p><p>...La estatua llegó hasta Nueva York en 214 cajas, de las cuales 36 sólo contenían tuercas y remaches, que debieron cruzar el Sena y, posteriormente, todo el Atlántico hasta llegar al destino, una odisea que se unió a un ensamblaje de 4 meses?.</p><p>...Desde su montaje y hasta 1902, la Estatua de la Libertad fue el faro de Nueva York con un potente haz de luz que alcanzaba los 39 kilómetros de distancia?.</p>",
		TajMahal: "<p>El <b>Taj Mahal</b> es un complejo de edificios construido entre 1631 y 1648 en la ciudad de <b>Agra</b>, estado de <b>Uttar Pradesh (India)</b>, a orillas del río <b>Yamuna</b>, por el emperador musulmán <b>Shah Jahan</b> de la dinastía mogola.</p> <p>El Taj Mahal es considerado el más bello ejemplo de arquitectura mogola, estilo que combina elementos de las arquitecturas islámica, persa, india e incluso turca.</p>",
		TajMahal2: "<h3>¿Sabías que...</h3><p>...Para construir un monumento tan majestuoso como el Taj Mahal se necesitó el trabajo de más de 20.000 hombres y de 1.000 elefantes?</p><p>...Los arquitectos más importantes del imperio participaron en su construcción? Se dice que, una vez finalizado el trabajo, mandaron cortar sus manos para que nunca pudieran volver a diseñar construcción parecida en ningún lugar. Otras historias cuentan que el emperador también mandó dejarles ciegos.</p><p>..Estuvo a punto de ser demolido por los ingleses a principios del siglo XIX? Al parecer su objetivo era aprovechar el mármol de la fachada para venderlo en subastas.</p><p>...El Taj Mahal puede adquirir más de 10 tonalidades de colores distintos dependiendo de la hora del día y la incidencia de la luz sobre él?</p>",
		SidneyOpera: "<p>La <b>Ópera de Sídney</b> o <b>Casa de la Ópera de Sídney</b>, situada en la ciudad de <b>Sídney</b>, estado de <b>Nueva Gales del Sur</b>, <b>Australia</b>, es uno de los edificios más famosos y distintivos del siglo XX. Declarado en 2007 Patrimonio de la Humanidad, fue diseñado por el arquitecto danés <b>Jørn Utzon</b> en 1957 e inaugurado el 20 de octubre de 1973, con presencia de la reina <b>Isabel II</b> en su papel de reina de Australia.</p>",
		SidneyOpera2: "<h3>¿Sabías que...</h3><p>...El diseño de Jørn Utzon ganó el concurso y se impuso a diseños más tradicionales, pero no antes de haber sido desestimado por ser considerado como 'demasiado ambicioso'?.</p><p>...El 20 de octubre de 1973, casi 17 años después de que el proyecto de Utzon fuera elegido, se inauguró la Opera de Sy­dney, con un coste superior a los 102 millones de dólares?.</p><p>...La Ópera de Sydney tiene cuatro auditorios principales para Ópera, danza, conciertos y teatro. Realiza más de 2.400 eventos anuales, por lo que no sólo es un impresionante edificio, sino que también es una referencia para el arte?.</p><p>...El edificio es singular en todos sus ángulos, el tejado tiene 67 metros de altura, tiene 27.000 toneladas de azulejos suecos, y más de 1.000.000 de piezas. 4.5 millones de visitas al año?.</p>",
		TorreEiffel: "<p>La <b>torre Eiffel</b> es una estructura de hierro pudelado diseñada por <b>Maurice Koechlin</b> y <b>Émile Nouguier</b>, y construida por el ingeniero francés <b>Alexandre Gustave Eiffel</b> y sus colaboradores para la Exposición universal de 1889 en <b>París</b>?.</p><p>Situada en el extremo del <b>Campo de Marte</b> a la orilla del río <b>Sena</b>, este monumento parisino, símbolo de <b>Francia</b> y su capital, es la estructura más alta de la ciudad con 324 metros de altura?.</p>",
		TorreEiffel2: "<h3>¿Sabías que...</h3><p>...Aunque su construcción había sido planificada para 12 meses, tardó dos años, dos meses y cinco días (Desde enero de 1887 hasta el 31 de marzo de 1889)?.</p><p>...Es considerado el monumento más valioso en Europa, con un valor de 544 mil millones de dólares para la economía francesa, casi una quinta parte del producto interno bruto del país?.</p><p>...Es el monumento que cobra entrada más visitado del mundo, con 7,1 millones de turistas cada año?.</p><p>...Inicialmente fue utilizada para pruebas del ejército con antenas de comunicación, hoy sirve, además de atractivo turístico, como emisora de programas radiofónicos y televisivos?.</p><p>...Tiene aproximadamente 2 millones 500 mil remaches que pusieron 250 trabajadores y en la construcción de sus piezas y ensamblajeestuvieron involucrados más de medio centenar de ingenieros que hicieron cerca de 5 mil 300 dibujos durante dos años?.</p>"
	}]
};